---
- name: "Создание директории .ssh для пользователя {{ user_1 }}"
  file:
    path: /home/{{ user_1 }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ user_1 }}"
    group: "{{ user_1 }}"

- name: "Добавление публичного ключа для пользователя {{ user_1 }} в authorized_keys"
  authorized_key:
    user: "{{ user_1 }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: "Выключаем файл подкачки"
  mount:
    path: "{{ item }}"
    fstype: "swap"
    state: "absent"
  loop:
    - "swap"
    - "none"

- name: "Загружаем модуль br_netfilter и overlay в ядро"
# Модуль br_netfilter расширяет возможности netfilter
  modprobe:
    name: "{{ item }}"
    state: "present"
  loop:
    - "br_netfilter"
    - "overlay"

- name: "Добавляем модуль br_netfilter для автозагрузки" 
  copy:
    content: |
      br_netfilter
      overlay
    dest: "/etc/modules-load.d/containerd.conf"
    mode: "0644"

- name: "Включаем обработку трафика через bridge в netfilter"
  sysctl:
    name: "{{ item.split('=')[0] }}"
    value: "{{ item.split('=')[1] }}"
    sysctl_file: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: present
  loop:
  - "net.ipv4.ip_forward=1"
  - "net.bridge.bridge-nf-call-iptables=1"
  - "net.bridge.bridge-nf-call-ip6tables=1"

- name: "Загрузка архива containerd-{{ containerd_version }} с Github"
  become: true
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz
    dest: /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz

- name: "Распаковка архива containerd-{{ containerd_version }} с Github"
  unarchive:
    src: /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
    extra_opts: "--gzip"

- name: "Копируем файлы containerd-{{ containerd_version }} в /usr/local/bin"
  become: true
  copy:
    remote_src: yes
    src: /tmp/bin/
    dest: /usr/local/bin/
    force: yes

- name: "Создание директории /etc/containerd"
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: "Создание конфигурации по умолчанию для containerd"
  become: true
  shell: containerd config default | tee /etc/containerd/config.toml

- name: "Установка systemd сервиса для containerd"
  become: true
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /etc/systemd/system/containerd.service

- name: "Загружаем компонент runc v{{ runc_version }}"
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64
    dest: /tmp/runc.amd64

- name: "Установка компонента runc v{{ runc_version }}"
  become: true
  command: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

- name: "Загружаем сетевые плагины CNI v{{ cni_plugin_version }}"
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugin_version }}/cni-plugins-linux-amd64-v{{ cni_plugin_version }}.tgz
    dest: /tmp/cni-plugins-linux-amd64-v{{ cni_plugin_version }}.tgz

- name: "Создание директории /opt/cni/bin для сетевых плагинов"
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: "Распаковка сетевых плагинов CNI v{{ cni_plugin_version }}"
  unarchive:
    src: /tmp/cni-plugins-linux-amd64-v{{ cni_plugin_version }}.tgz
    dest: /opt/cni/bin
    remote_src: yes
    extra_opts: "--gzip"

- name: "Перезагрузка демонов systemd"
  become: true
  systemd:
    daemon_reload: true

- name: "Включение и запуск контейнера containerd"
  become: true
  systemd:
    name: containerd
    enabled: true
    state: started

- name: "Добавляем конфигурацию с указанием socket containerd для crictl"
  copy:
    content: |
      runtime-endpoint: unix:///var/run/containerd/containerd.sock
    dest: "/etc/crictl.yaml"
    mode: "0644"

- name: "Установка вспомогательных пакетов"
  become: true
  apt:
    name:
      - curl
      - wget
      - gnupg
      - sudo
      - iptables

    state: present
    update_cache: yes

- name: "Скачивание GPG-ключа"
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: "/tmp/Release.key"

- name: "Конвертация GPG-ключа в формат keyring"
  command: "gpg --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key"

- name: "Установка прав доступа к ключу"
  file:
    path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    mode: '0644'

- name: "Создание файла источника для Kubernetes"
  copy:
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /\n"
    dest: "/etc/apt/sources.list.d/kubernetes.list"
    mode: '0644'

- name: "Установка бинарей: kubeadm, kubectl, kubelet"
  become: true
  apt:
    name:
      - kubelet
      - kubectl
      - kubeadm
    state: present
    update_cache: yes

# MASTER TASKS
- name: "Установка вспомогательных пакетов на master hosts"
  become: true
  apt:
    name:
      - keepalived
      - haproxy
    state: present
    update_cache: yes
  when: "'k8s_master' in group_names"

- name: keepalived. Создание конфигурационного файла демона keepalived /etc/keepalived/keepalived.conf
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  when: "'k8s_master' in group_names"

- name: keepalived. Создание скрипта для проверки доступности хостов /etc/keepalived/check_apiserver.sh
  template:
    src: templates/check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    mode: '0755'
  when: "'k8s_master' in group_names"

- name: "keepalived. Включение и запуск демона"
  systemd:
    name: keepalived
    enabled: true
    state: restarted
  when: "'k8s_master' in group_names"

- name: haproxy. Создание конфигурационного файла демона haproxy /etc/haproxy/haproxy.cfg
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when: "'k8s_master' in group_names"

- name: "haproxy. Включение и запуск демона"
  systemd:
    name: haproxy
    enabled: true
    state: restarted
  when: "'k8s_master' in group_names"

- name: Добавим пользователя {{ user_1 }} в группу sudo
  ansible.builtin.user:
    name: "{{ user_1 }}"
    groups: sudo
    append: yes  # Добавить в группу, не удаляя из других групп

- name: Настройка sudo без пароля для пользователя {{ user_1 }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ user_1 }}'
    line: '{{ user_1 }} ALL=(ALL) NOPASSWD: ALL'

- name: Перезагрузка системы
  ansible.builtin.reboot:
    msg: "Перезагрузка инициирована Ansible"
    connect_timeout: 5  # Время ожидания подключения
    reboot_timeout: 600  # Время ожидания перезагрузки
