---
- name: k8s_prepare_all
  become: yes
  become_method: su
  become_user: root
  hosts: k8s
  roles:
    - k8s_prepare_all
  vars_prompt:
  - name: remote_user
    prompt: "Введите значение для remote_user"
    private: true
  - name: root_pass
    prompt: "Введите значение для root_pass"
    private: true
  vars_files:
  - vars/main.yml
