apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.88.90-192.168.88.100
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2-first-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
