---
# vars file for k8s_prepare
k8s_version: "1.32"
user_1: "{{ remote_user }}"
containerd_version: "2.0.4"
runc_version: "1.2.6"
cni_plugin_version: "1.6.2"
ansible_become_pass: "{{ root_pass }}"
ansible_ssh_pass: "{{ root_pass }}"
keepalived_virtual_ip: "192.168.88.20"
keepalived_pass: "ZqSj#f1G"
apiserver_port_frontend: "8888"

# master node
servers:
  - { name: "node1", ip: "192.168.88.21", port: "6443" }
  - { name: "node2", ip: "192.168.88.22", port: "6443" }
  - { name: "node3", ip: "192.168.88.23", port: "6443" }
