all:
    children:
        k8s:
            hosts:
                k8s-control1.{{ host_domain }}:
                k8s-worker1.{{ host_domain }}:
                k8s-worker2.{{ host_domain }}:
        k8s_master:
            hosts:
                k8s-control1.{{ host_domain }}:
